### PR TITLE
Semi-massive reorganization of the supporting code

### PR DESCRIPTION
**Pull request by iamvery**
This PR touches nearly all the supporting code, but the overview of the change is relatively straight-forward.
1. Extract modules for the different pieces of the code. Driving motivation here is painting a clearer picture of the moving pieces.
2. Get the examples agent under supervision. This isn't particularly important since the code is not long running, but it's nice and perhaps good practice to keep processes under supervision.
3. Kill the remaining "checks", keeping things warning-free.

### CODE REVIEW

**Comment by wolfbrain** [comment]
:eyes: @killpack

**Comment by wolfbrain** [comment]
:eyes: @sebastiangeiger

**Comment by nathanl** [comment]
I don't understand everything you did, but the organization looks better and I like getting rid of `Koans.Check`.

**Comment by iamvery** [comment]
Thanks for checking things out!

**Pull request merged**
